# Changes here will be overwritten by Copier
_commit: 0.6.1
_src_path: https://github.com/nlesc/python-template.git
copyright_holder: domhnall carlin
email: domhnallcarlin@gmail.com
full_name: domhnall carlin
github_organization: https://github.com/domhnallc
keywords: dessert,sweets
license: GNUv3
package_name: baklava
package_short_description: A test package for RSECon24 training
template_profile: minimum
version: 0.1.0
